# Generated by Django 3.2.6 on 2021-09-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='sum_rub',
        ),
    ]
