# Generated by Django 3.2.6 on 2021-09-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210908_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.user'),
            preserve_default=False,
        ),
    ]
