# Generated by Django 3.2.6 on 2021-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_balance_sum_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='sum_rub',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
