# Generated by Django 3.2.6 on 2021-09-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
