# Generated by Django 3.2.6 on 2021-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
